apiVersion: skaffold/v1beta10
kind: Config
build:
  artifacts:
  - image: blcksdescribeinstances
    context: build/blcksdescribeinstances
    docker:
      noCache: true
deploy:
  kustomize:
    path: github.com/pnetwork/pnbase//blcksdescribeinstances/?ref=master